// This file is auto-generated by update-mod-version.js
export const NAME = "Boss Mode";
export const ID = "BossMode";
export const AUTHOR = "thinkadrian";
export const DESCRIPTION = "Adds a Boss Mode overlay with quick access to upgrades, including a toggle button and keyboard shortcut.";
export const MOD_VERSION = "0.1.0";
export const GAME_VERSION = 2.031;
export const DATE = "09/02/2026";
export const ALLOW_STEAM_ACHIEVS = 1;
